### ISSUE TITLE
Received NaN for the 'cx' attribute.

### ISSUE THREAD

**Issue by awatson1978** [hgraph-os/hgraph-react#16]
Hello, 
We're trying to adjust the metrics of hGraph to do a categorical view of FHIR resource collections, in which case most all values will be 0 to N.  So, we're trying to feed a dataset into hGraph that looks roughly like this:

```
let collectionBuckets = [
  {
    "id": "allergyIntoleranceCount",
    "label": "Allergy Intolerances",
    "healthMin": 0,
    "healthMax": 10,
    "absoluteMin": 0,
    "absoluteMax": 100,
    "value": 5,
    "weight": 10,
    "unitLabel": "records"
  },
  {
    "id": "conditionCount",
    "label": "Conditions",
    "healthMin": 0,
    "healthMax": 20,
    "absoluteMin": 0,
    "absoluteMax": 200,
    "value": 14,
    "weight": 10,
    "unitLabel": "records"
  },
  {
    "id": "diagnosticReportCount",
    "label": "Diagnostic Reports",
    "healthMin": 0,
    "healthMax": 20,
    "absoluteMin": 0,
    "absoluteMax": 200,
    "value": 6,
    "weight": 10,
    "unitLabel": "records"
  },
  {
    "id": "encounterCount",
    "label": "Encounters",
    "healthMin": 0,
    "healthMax": 100,
    "absoluteMin": 0,
    "absoluteMax": 1000,
    "value": 22,
    "weight": 10,
    "unitLabel": "records"
  }
];
```

When it renders, all the points are at the center origin, and aren't picking up the values.
![Screen Shot 2020-12-02 at 8 51 26 AM](https://user-images.githubusercontent.com/675910/101520384-06d64180-394a-11eb-9f4d-10a639eec94a.png)

Digging into the console, we're getting a `Received NaN for the 'cx' attribute.` error message.
![Screen Shot 2020-12-02 at 8 59 10 AM](https://user-images.githubusercontent.com/675910/101520369-02118d80-394a-11eb-8035-c244de5f0c95.png)

**Comment by awatson1978** [comment]
Here's a reproduction of the problem.  Any help would be much appreciated.
https://codesandbox.io/s/hgraph-demo-1humf?file=/index.js

**Comment by craigmcginley** [comment]
Ah, you want `healthyMin` and `healthyMax` (adding a 'y' after 'health' in each property). I think that fixes the sandbox you linked. Confirm if it's still an issue or not after updating those properties in your code.

**Comment by awatson1978** [comment]
Ah ha!  I think that fixed the issue!  Thank you!!!
